name: Deploy Lambdas to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        function:
          - name: ImageThumbnailGenerator
            lambdaName: Bytebox-ImageThumbnailGenerator-Dev
            awsFunctionName: Bytebox-ImageThumbnailGenerator-Dev
          - name: PdfThumbnailGenerator
            lambdaName: Bytebox-PdfThumbnailGenerator-Dev
            awsFunctionName: Bytebox-PdfThumbnailGenerator-Dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Amazon Lambda Tools
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
          
      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y python3-pip
          pip3 install awscli

      - name: Build and package Lambdas
        run: |
          dotnet publish -c Release -r linux-x64 -p:PublishReadyToRun=true -o LambdaPublishOutput src/ByteBox.Lambdas.csproj
          cd LambdaPublishOutput
          zip -r ../LambdaDeploymentPackage.zip .
          cd ..

      - name: Deploy ${{ matrix.function.name }} to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
        run: |
          echo "Deploying ${{ matrix.function.name }} as ${{ matrix.function.awsFunctionName }}..."
          aws lambda update-function-code --function-name ${{ matrix.function.awsFunctionName }} --zip-file fileb://LambdaDeploymentPackage.zip
